### ISSUE TITLE
Implementation will leak exceptions across C API boundaries, have no way of indicating failure to callers.

### ISSUE THREAD

**Issue by CrimsonGuy** [LaurentGomila/CSFML#32]
Some examples of problems here:

* All the creation factories 'return new Foo;'  In the case of memory failure, this doesn't generate nullptr, it throws std::bad_alloc.

* Any function that internally uses STL functions could be throwing (internal bad_alloc's, or other STL-thrown exceptions).  Here it is both a problem that the function is throwing across a C-boundary, and that even if you surround with a try/catch, you have no way of signalling any failure to a caller.

For example, sfHttpRequest_setUri.  This internally is using the std::string::operator= to copy the character array in SFML.  Here, you can get a bad_alloc, or a length_error (http://en.cppreference.com/w/cpp/string/basic_string/operator%3D).  If you correctly catch the exception before leaking it to your caller, you have no way of indicating any failure with the signature:

void sfHttpRequest_setUri(sfHttpRequest* httpRequest, const char* uri);

This is where C and C++ API's need to be slightly different.  You can't just pass the 'this' pointer as the first parameter to every function, because your primary error propagating mechanism (exceptions) does not exist.

**Comment by zsbzsb** [comment]
What would you suggest doing instead?

**Comment by LaurentGomila** [comment]
There's no useful way to treat a std::bad_alloc exception, except quitting the application immediately. That's why it is rarely handled explicitly. STL container exceptions are not supposed to be thrown (they are more programming errors than runtime exceptions) and if you ever get one then you can report a bug here.

Let's focus on real issues.

**Comment by zsbzsb** [comment]
>There's no useful way to treat a std::bad_alloc exception

This is why I asked what @CrimsonGuy would propose we do instead, because I also thought there is no better way to handle the situation.

**Comment by CrimsonGuy** [comment]
Typically if you want to expose a safe C API that's actually implemented in C++ under the covers, your function signatures change from:

ReturnType Foo::GetBar(); + exceptions for badness

called as such:
Foo foo;
ReturnType t = foo.GetBar();

to

extern "C" ErrorCodeType Foo_GetBar(_In_ Foo* foo, ReturnType* bar)

called as such:
Foo foo;
Foo_Initialize(&foo);

Bar bar;
ErrorCodeType error = Foo_GetBar(&foo, &bar);

And you typically wrap the implementation of your exported C functions with a try/catch that converts exceptions to error codes.  

I come from a field where crashes and unexpected shutdown are not okay, so we take the pains to do this sort of thing.  We make extensive use of RAII to implement transaction-like logic, and we need to make sure destructors run for all our objects in the event of a failure, which they don't for unhandled exceptions.  But perhaps for CSFML it's overkill.  As you say, STL exceptions are almost always dev error, and you probably don't have some grand memory-reclamation scheme in the face of a std::bad_alloc.  As long as your internal object types aren't doing any exception-throwing of their own, these are probably the only two things you need to deal with.  As long as you're okay with crashing instead of graceful exit in this case, then I think skipping this work is reasonable.

**Comment by LaurentGomila** [comment]
Thanks for raising this concern, it's always good to discuss technical points, even when it doesn't lead to a modification.
